### ISSUE TITLE
部署之后冷启动速度很慢

### ISSUE THREAD

**Issue by chenruifu** [serverless-components/tencent-nuxtjs#13]
![image](https://user-images.githubusercontent.com/19771516/96285234-3c794100-1011-11eb-8bbe-ce8785c788c2.png)
![image](https://user-images.githubusercontent.com/19771516/96285250-44d17c00-1011-11eb-9c1f-856d28d2b102.png)

正常得页面刷个3次才能正常

**Comment by yugasun** [comment]
可以通过配置 `staticConf` 来讲客户端静态资源上传到cos桶，来减少函数返回静态资源，从而减少单位时间函数执行次数，从而减少函数冷启动概率。
也可以通过腾讯云云函数的并发配置来减少冷启动，[官方文档](https://cloud.tencent.com/document/product/583/45757)

**Comment by chenruifu** [comment]
1
