### ISSUE TITLE
一直处于NuxtJsFunc Deploying...状态

### ISSUE THREAD

**Issue by bear-shchan** [serverless-components/tencent-nuxtjs#2]
拷贝了自己的项目代码以后，通过sls部署，会一直处于NuxtJsFunc Deploying(8000s+) 还没部署成功

**Comment by tinafangkunding** [comment]
hi 您好，感谢反馈！请问下您自己的项目代码包大概是多大？当前初步看是因为代码包过大，打包上传过程卡住的问题。

**Comment by bear-shchan** [comment]
> hi 您好，感谢反馈！请问下您自己的项目代码包大概是多大？当前初步看是因为代码包过大，打包上传过程卡住的问题。

是需要把node_modules目录也包含在内吗？我后来试着在node8.9.0环境下，部署tencent-nuxtjs项目所提供的tencent-nuxtjs/example，发现在删除了node_modules的情况下可以成功部署，但是访问地址会报缺少express的错。在不删除node_modules的情况下，sls部署也是会一直处于NuxtJsFunc Deploying的状态下，是我电脑的性能太差了吗？

**Comment by yugasun** [comment]
@bear-shchan 部署时执行 `serverless --debug`，把debug信息打印下，方便定位问题。

**Comment by scottwansz** [comment]
`D:\1. demo\serverlesss-nuxtjs>sls --debug

  DEBUG ─ Resolving the template's static variables.
  DEBUG ─ Collecting components from the template.
  DEBUG ─ Downloading any NPM components found in the template.
  DEBUG ─ Analyzing the template's components dependencies.
  DEBUG ─ Creating the template's components graph.
  DEBUG ─ Syncing template state.
  DEBUG ─ Executing the template's components graph.
  DEBUG ─ Compressing function nuxtjs-function file to D:\1. demo\serverlesss-nuxtjs\.serverless/nuxtjs-function.zip.

  28205s » NuxtjsFunc » canceled`
我出现同样的问题，我只是严格按[官方文档](https://cloud.tencent.com/document/product/1154/43007)走一遍，结果最后部署一步卡住了，跑了一晚上没完，最后手动取消了，白天跑过几次也不成功。

**Comment by scottwansz** [comment]
取消前发现‘.serverless/nuxtjs-function.zip’这个文件一直是0K，取消后这个文件就变成10M大小，感觉是打包的功能有问题。

**Comment by scottwansz** [comment]
我的环境是Windows，试过Git bash，Wiondws pwershell与command line，这三种都不行，看你们的视频演示的操作系统使用的是Linux，我手头也没有纯Linux，不过可以拿Wiondow10 自带的的Linux子系统试下。

**Comment by tinafangkunding** [comment]
收到反馈，这里应该是类似的问题。目前计划的一个优化方案是将 next.js  nuxt.js 等比较重的框架直接在云端 layer 中存储一份，这样可以减少本地打包压缩的压力

**Comment by fulus06** [comment]
我也是这个问题
![image](https://user-images.githubusercontent.com/12890684/80367623-065ad000-88be-11ea-9dd3-cb849604db02.png)

**Comment by fulus06** [comment]
DEBUG ─ Resolving the template's static variables.
  DEBUG ─ Collecting components from the template.
  DEBUG ─ Downloading any NPM components found in the template.
  DEBUG ─ Analyzing the template's components dependencies.
  DEBUG ─ Creating the template's components graph.
  DEBUG ─ Syncing template state.
  DEBUG ─ Executing the template's components graph.
  DEBUG ─ Compressing function nuxtjs-function file to H:\Tools\repository\svn\fulusco\webapp-station-custom\prototype.13143.xin\.serverless/nuxtjs-function.zip.

  488s » NuxtjsFunc » Deploying ..

**Comment by yugasun** [comment]
可以先参考：https://github.com/serverless-components/tencent-egg/issues/5 处理
