### ISSUE TITLE
[FAQ] 回答create-nuxt-app创建项目部署出现user code exception caught

### ISSUE THREAD

**Issue by sonofmagic** [serverless-components/tencent-nuxtjs#4]
有些用户出现

{
  "errorCode": -1,
  "errorMessage": "user code exception caught",
  "stackTrace": "Unexpected token export"
}

这个错误，本质上是由于作者在issue 1中添加了sls.js 用的commonjs2规范，而默认创建的nuxt
(不带express或koa)建立出来的项目的nuxt.config.js是的esm规范,这导致sls在require nuxt.config.js会跪，然后导致了这个错误。

所以出现这种问题，只需要把nuxt.config.js里的export default 改成 module.exports = ，然后重新部署就可以

**Comment by tinafangkunding** [comment]
@yugasun 辛苦帮忙看看哈

**Comment by sonofmagic** [comment]
@tinafangkunding 这个是群里有人出现这样的问题，我解决之后写的一个ref,不是bug issue那种，不需要查看。

**Comment by yugasun** [comment]
该问题在v2版本中已自动修复。

**Comment by juukee** [comment]
如果使用 层挂载node_modules的话，会出现以下错误
初步排查了本地项目情况，发现nuxt运行需要在本地用户目录生成这个目录，由于是severless上传的，默认没有自动生成，不知道是否需要你们官方在那个用户目录 下面增加这个文件
文件内容如下：
# .nuxtrc
telemetry.enabled=false

报错如下
```
{"errorCode":-1,"errorMessage":"user code exception caught","stackTrace":"Error: ENOENT: no such file or directory, open '/home/qcloud/.nuxtrc'\n    at Object.openSync (fs.js:438:3)\n    at Object.writeFileSync (fs.js:1189:35)\n    at write (/opt/node_modules/rc9/dist/index.js:87:6)\n    at update (/opt/node_modules/rc9/dist/index.js:106:3)\n    at Object.updateUser (/opt/node_modules/rc9/dist/index.js:112:10)\n    at updateUserNuxtRc (/opt/node_modules/@nuxt/telemetry/dist/module.js:30:6)\n    at ModuleContainer.telemetryModule (/opt/node_modules/@nuxt/telemetry/dist/module.js:511:5)"}
```

**Comment by yugasun** [comment]
@juukee 看了下，最新的 Nuxt.js 引入了 `telemetry` 来对用户使用进行数据收集，也是导致文件 `.nuxtrc` 读写报错，可以在执行 `nuxt build` 是输入 `n` 而不使用该模块。

当然直接在 `nuxt.config.js` 中配置 `telemetry` 为 `false` 也是可以的。

**Comment by sonofmagic** [comment]
要禁用 telemetry 用户使用进行数据收集，只需要在nuxtConfig里把`telemetry`设置成 `false` 就行
ref: https://github.com/nuxt/nuxt.js/blob/dev/packages/config/src/options.js#L493
