### ISSUE TITLE
sls --debug 内存溢出

### ISSUE THREAD

**Issue by wq0613** [serverless-components/tencent-nuxtjs#7]
执行几分钟以后就内存溢出，本地打包部署都不会遇到这种问题

<--- Last few GCs ---> Deploying

[8048:000001CA003D9450]   321003 ms: Mark-sweep 1992.1 (2075.4) -> 1980.7 (2076.9) MB, 831.5 / 3.3 ms  (average mu = 0.137, current mu = 0.059) allocation failure scavenge might not succeed
[8048:000001CA003D9450]   321917 ms: Mark-sweep 1993.7 (2076.9) -> 1983.2 (2079.4) MB, 868.6 / 3.2 ms  (average mu = 0.095, current mu = 0.051) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF708AA4DDD]
    1: StubFrame [pc: 00007FF708AA5FD7]
Security context: 0x0270fe2c08d1 <JSObject>
    2: resolve [0000010DA5D8D4E9] [path.js:~130] [pc=00000046256EBB0D](this=0x010da5d82b59 <Object map = 00000005170AEF19>)
    3: arguments adaptor frame: 1->0
    4: lstat [0000010DA5DBAEF9] [fs.js:~886] [pc=00000046256F0E6B](this=0x010da5d82811 <Object map = 00000005170B8C99>,0x004d4171b531 <String[206]\: D:\\\x98...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200512.171943.8048.0.001.json
Node.js report completed
 1: 00007FF707EA363F napi_wrap+128063
 2: 00007FF707E42836 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+35142
 3: 00007FF707E434F6 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+38406
 4: 00007FF708659F4E private: void __cdecl v8::Isolate::ReportExternalAllocationLimitReached(void) __ptr64+94
 5: 00007FF708642021 public: class v8::SharedArrayBuffer::Contents __cdecl v8::SharedArrayBuffer::Externalize(void) __ptr64+833
 6: 00007FF70850E57C public: static void __cdecl v8::internal::Heap::EphemeronKeyWriteBarrierFromCode(unsigned __int64,unsigned __int64,class v8::internal::Isolate * __ptr64)+1436
 7: 00007FF7085197D0 public: void __cdecl v8::internal::Heap::ProtectUnprotectedMemoryChunks(void) __ptr64+1312
 8: 00007FF7085162F4 public: static bool __cdecl v8::internal::Heap::PageFlagsAreConsistent(class v8::internal::HeapObject)+3204
 9: 00007FF70850BB13 public: bool __cdecl v8::internal::Heap::CollectGarbage(enum v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReason,enum v8::GCCallbackFlags) __ptr64+1283
10: 00007FF70850A184 public: void __cdecl v8::internal::Heap::AddRetainedMap(class v8::internal::Handle<class v8::internal::Map>) __ptr64+2452
11: 00007FF70852B36D public: class v8::internal::Handle<class v8::internal::HeapObject> __cdecl v8::internal::Factory::NewFillerObject(int,bool,enum v8::internal::AllocationType,enum v8::internal::AllocationOrigin) __ptr64+61
12: 00007FF708290C51 ??4iterator@JumpTableTargetOffsets@interpreter@internal@v8@@QEAAAEAV01234@$$QEAV01234@@Z+1665
13: 00007FF708AA4DDD public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+546637
14: 00007FF708AA5FD7 public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+551239
15: 00000046256EBB0D

**Comment by tinafangkunding** [comment]
可以参考这个 issue 解决 https://github.com/serverless-components/tencent-egg/issues/5

此外，可以使用 v2 版本的进行部署。https://github.com/serverless-components/tencent-nuxtjs/tree/v2
